### PR TITLE
Port to Python3 and other fixes [GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**
Tested, works on Sugar Desktop Environment. Consider testing on an OLPC, before merging because this uses sensors like Microphone and Speaker. Tested with a normal microphone.

## Screenshots
Screenshot from 2019-12-18 19-42-19
Screenshot from 2019-12-18 19-43-23
Screenshot from 2019-12-18 19-43-30

## Disclaimer
While testing, we might fall into the tendency of changing the Hertz values. Testing on a subwoofer, at very high or very low frequency, can break your Desktop, Glass Windows and anything fragile.  :rofl: 
If you are an experimenting person, try Frequency 60 Hz and 1500 Hz, on a computer with a GPU, and see how your display goes off. (The fan rotates opposite, my VGA blinked, lol)

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested on the OLPC Infinity laptop. This traceback occurs;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Measure.activity/measure.py", line 187, in __init__
    self.audiograb = ag(self.wave.new_buffer, self)
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 112, in __init__
    self.master = self.get_master()
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 467, in get_master
    pos = output.find('Front Left:')
TypeError: a bytes-like object is required, not 'str'
```

I suggest checking all uses of `subprocess` module.

Regarding your computer, it should not do that, no matter what audio tones are generated, provided they are within safe hearing range.  I suggest having it checked by a technician.  Especially the power supply.  Anything that causes a cooling fan to reverse could be a safety issue.

On the other hand, if you found the activity changed your volume levels, that's not what the activity should do, so we should try to fix that.

**Comment by srevinsaju** [comment]
@quozl , I have fixed that error on https://github.com/sugarlabs/Measure/pull/16/commits/a351219bd34690a2176d6461c193aed96a559b44 and some more errors on running this on a sugar iso compared to the development environment. I guess this activity requires vigorous testing, I have tried pressing each buttons until all the Tracebacks were fixed. However, good thing is that, the program doesn't crash at any instances, but that doesn't hold good. The current commit fixed the error pointed by you and some more discovered errors. 

> Regarding your computer, it should not do that, no matter what audio tones are generated, provided they are within safe hearing range. I suggest having it checked by a technician. Especially the power supply. Anything that causes a cooling fan to reverse could be a safety issue.

Thats because, I was crazy will very low values and very high ones. I have a huge subwoofer, almost near my GPU, so thats the problem. It should work on the OLPC though. The only solution to this is to limit the frequencies within the safe range,  see >
> exposure to vertical vibrations in the 5-10 Hz range generally causes resonance in the thoracic-abdominal system

According to colorusage.arc.nasa.gov
>Sound between 5-8Hz at very high volume can flicker your CFL tube. 

These are normally experienced while you try studio recording, or playing a base drum in a small room, but thats absolutely fine. and even with a OLPC, its finer, I suppose.
One solution, the limit frequency , allowed to be entered by the kid, however has one disadvantage:
It will limit the student's capacity to experiment to varying frequencies of sound
I feel its absolutely ok, as long as your DISCLAIMER is followed, using sugar for ONLY educational purposes :P

**Comment by quozl** [comment]
Thanks.  I've also gotta backport this to a Python 2 branch, and that is harder to do with the way the patches are laid out.  Apart from where freq is made positive if it is negative, were there any other fixes to the program?

**Comment by srevinsaju** [comment]
@quozl, nope, those fixes are all related to the bytes and strings, all the strings had to be converted to bytes. nothings wrong with the main program except got the Freq thingy

**Comment by quozl** [comment]
Thanks.  Tested.  When `csound` is not available, the exception that occurs seems to prevent further use of the microphone until the activity is restarted?

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Measure.activity/tuning_toolbar.py", line 363, in play_sound
    self._play_sinewave(freq, 5000, 1)
  File "/usr/share/sugar/activities/Measure.activity/tuning_toolbar.py", line 396, in _play_sinewave
    check_output(['csound', path], 'call to csound failed?')
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 759, in check_output
    output = subprocess.check_output(command)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Can you please briefly describe the extent or coverage of your testing?

**Comment by quozl** [comment]
a1999c9f174df0dc1444ec79ecbc9b78e010b896 ("Fix use of absolute value of frequency") has been committed on _python2_ branch.

**Comment by srevinsaju** [comment]
Coverage: I tried pressing all the buttons and all possible methods under _right conditions_ . Right Conditions include running the activity after installing csound.
The same problem will be faced in `Music-keyboard-activity` . The master branch does not handle errors, and as long as it doesn't, we can't do anything.  One option is to create a shell script to install the necessary modules.

**Comment by srevinsaju** [comment]
@quozl , we can force stop the activity if csound is not found, will it however keep the microphone  in a unusable state?

**Comment by quozl** [comment]
Okay, you're saying because _master_ does this (I didn't know that, thanks), it's not a porting problem.  It is a latent problem that happens to have been exposed by testing.  I'll raise an issue then.

**Comment by srevinsaju** [comment]
:+1:

**Pull request merged**
